OUTPUT_MODE_RAW = "raw"
OUTPUT_MODE_SMART = "smart"

NEMOTRON_REASONING_BUDGET_DEFAULT = 4096
NEMOTRON_REASONING_BUDGET_MAX = 4096
NEMOTRON_REASONING_PRINT_LIMIT_DEFAULT = 600
NEMOTRON_REASONING_PRINT_LIMIT_MAX = 4000

WINDOWS_SW_HIDE = 0
WINDOWS_SW_SHOW = 5

OVERLAY_WIDTH = 160
OVERLAY_HEIGHT = 48
OVERLAY_FPS = 60
